using Asp.Versioning;
using EventOpsOracle.Application.Notifications.Commands;
using EventOpsOracle.Application.Notifications.Queries;
using EventOpsOracle.Domain.Interfaces;
using EventOpsOracle.Shared.Common;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EventOpsOracle.Api.Controllers;

/// <summary>
/// The recipient's own notification inbox, fed by the notification platform.
///
/// Distinct from AnnouncementsController: an announcement is a message an admin
/// composes and broadcasts, while these are generated by business events
/// (assignments, cancellations, payments) across every channel. The in-app copy
/// is what this controller serves.
///
/// Deliberately NOT permission-gated. Crew and vendors hold no notifications:*
/// permission, and every route is scoped to the authenticated caller's own id, so
/// the identity in the token IS the authorization. No route accepts a user id
/// from the client -- that would be an invitation to read someone else's inbox.
/// </summary>
[ApiController]
[ApiVersion("1.0")]
[Route("api/v{version:apiVersion}/notifications")]
[Authorize]
[Produces("application/json")]
public sealed class NotificationsController : ControllerBase
{
    private readonly IMediator    _mediator;
    private readonly ICurrentUser _currentUser;

    public NotificationsController(IMediator mediator, ICurrentUser currentUser)
    {
        _mediator    = mediator;
        _currentUser = currentUser;
    }

    /// <summary>The caller's notifications, newest first.</summary>
    [HttpGet("mine")]
    [ProducesResponseType(typeof(ApiResponse<MyNotificationsDto>), 200)]
    public async Task<IActionResult> Mine(
        [FromQuery] bool unreadOnly = false,
        [FromQuery] int  skip       = 0,
        [FromQuery] int  take       = 30,
        CancellationToken ct        = default)
    {
        var result = await _mediator.Send(
            new GetMyNotificationsQuery(_currentUser.UserId!.Value, unreadOnly, skip, take), ct);

        if (result.IsFailure)
            return BadRequest(ApiResponse.Fail(result.Error.Message));

        return Ok(ApiResponse<MyNotificationsDto>.Ok(result.Value));
    }

    /// <summary>
    /// Unread count for the bell badge. A separate endpoint because the badge is
    /// polled and rendered on every page, and it must not pay to render thirty
    /// message bodies just to display a number.
    /// </summary>
    [HttpGet("unread-count")]
    [ProducesResponseType(typeof(ApiResponse<int>), 200)]
    public async Task<IActionResult> UnreadCount(CancellationToken ct)
    {
        var result = await _mediator.Send(
            new GetMyNotificationsQuery(_currentUser.UserId!.Value, UnreadOnly: true, Skip: 0, Take: 1), ct);

        if (result.IsFailure)
            return BadRequest(ApiResponse.Fail(result.Error.Message));

        return Ok(ApiResponse<int>.Ok(result.Value.UnreadCount));
    }

    /// <summary>Marks one notification read. Idempotent.</summary>
    [HttpPost("{id:guid}/read")]
    [ProducesResponseType(typeof(ApiResponse<int>), 200)]
    public async Task<IActionResult> MarkRead(Guid id, CancellationToken ct)
    {
        var result = await _mediator.Send(
            new MarkNotificationsReadCommand(_currentUser.UserId!.Value, new[] { id }), ct);

        if (result.IsFailure)
            return BadRequest(ApiResponse.Fail(result.Error.Message));

        // 200 even when nothing changed: the row may already be read, or may not
        // be the caller's. Distinguishing those two would confirm that someone
        // else's notification id exists, which is not the client's business.
        return Ok(ApiResponse<int>.Ok(result.Value));
    }

    /// <summary>Marks everything unread as read, and reports how many.</summary>
    [HttpPost("read-all")]
    [ProducesResponseType(typeof(ApiResponse<int>), 200)]
    public async Task<IActionResult> MarkAllRead(CancellationToken ct)
    {
        var result = await _mediator.Send(
            new MarkNotificationsReadCommand(_currentUser.UserId!.Value), ct);

        if (result.IsFailure)
            return BadRequest(ApiResponse.Fail(result.Error.Message));

        return Ok(ApiResponse<int>.Ok(result.Value));
    }
}
